name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install Dependencies
        run: npm ci
      - name: Build PigTracks
        run: npm run build
      - name: test PigTracks
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
